version: '3.2'
services:
  app:
    image: "shooting-backend:${TAG}"
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=shooting.letscode.it
      - VIRTUAL_PORT=8080
      - SPRING_DATA_MONGODB_URI=mongodb://shooting_mongo:27017/shooting
    networks:
      - nginx-proxy
      - shooting-network
    depends_on:
      - mongodb

  mongodb:
    image: mongo:4.4.6
    container_name: shooting_mongo
    restart: unless-stopped
    environment:
      - 'MONGO_INITDB_DATABASE=shooting'
    networks:
      - shooting-network

networks:
  nginx-proxy:
    external:
      name: nginx-proxy
  shooting-network:
