version: '3.2'
services:
  app:
    image: "shooting-backend:${TAG}"
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=shooting.letscode.it
      - VIRTUAL_PORT=8080
    networks:
      - nginx-proxy

  mongo:
    image: mongo:4.4.10
    container_name: mongodb
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    networks:
      - shooting-network

networks:
  nginx-proxy:
    external:
      name: nginx-proxy
  shooting-network:

volumes:
  mongo_data:
